{% set name = "ascii-art" %}
{% set version = "6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/art/art-{{ version }}.tar.gz
  sha256: 417fea674bff8cea7ed058291ad1b81a6032dfce5152f28e629fa4a798a2c14c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - art = art.__main__:main

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5

test:
  imports:
    - art
  commands:
    - pip check
    - art test2
  requires:
    - pip

about:
  home: https://www.ascii-art.site
  summary: ASCII Art Library For Python
  dev_url: https://github.com/sepandhaghighi/art
  license: MIT
  license_file: LICENSE
  description: |
    ASCII art is also known as "computer text art".
    It involves the smart placement of typed special characters or
    letters to make a visual shape that is spread over multiple lines of text.
    ART is a Python lib for text converting to ASCII art fancy.
extra:
  recipe-maintainers:
    - thewchan
    - sepandhaghighi
    - sadrasabouri
