{% set name = "ascii-art" %}
{% set version = "5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/art/art-{{ version }}.tar.gz
  sha256: 6a311ec0a227c6554c6789e91e74c3f2c86453a2a8e76947788695b7a91ccff0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - art
  commands:
    - pip check
    - python -m art test2
  requires:
    - pip

about:
  home: https://www.ascii-art.site
  summary: ASCII Art Library For Python
  dev_url: https://github.com/sepandhaghighi/art
  license: MIT
  license_file: LICENSE
  description: |
    ASCII art is also known as "computer text art".
    It involves the smart placement of typed special characters or
    letters to make a visual shape that is spread over multiple lines of text.
    ART is a Python lib for text converting to ASCII art fancy.
extra:
  recipe-maintainers:
    - thewchan
    - sepandhaghighi
    - sadrasabouri
